# Generated by Django 3.2.13 on 2022-10-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('score', models.FloatField()),
                ('words_num', models.IntegerField()),
                ('timelength', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
