# Generated by Django 3.2.13 on 2022-10-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblist', '0003_auto_20221014_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubelink',
            name='timelength',
            field=models.CharField(max_length=200),
        ),
    ]
